### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [bob-reus/romain-rolland_jean-christophe_gilbert-cannan#1]
- chapter-7-2 line 28: the blockquote should not have `<br/>`s, those should each be `<p>` (with  `class="continued"` if it's the same speaker)
- in chapter-8-1 and chapter-9-2 there are epilogues attached in those files, styled with page break css. But those should just be in their own files, with the page break css removed. Also note that the data-parent attribute is incorrect on the chapter 8-1 epilogue.
- The blockquote CSS selectors for chapter 7-1 can be replaced with a class, because we have a class of elements to style.
- In chapter-10-4, the text selected by `#chapter-10-4 > p:nth-child(142)` is actually I think a caption for the figure right below it. So just make it a `<figcaption>` child of the`<figure>` and style appropriately.
- Missing some figure CSS: 
 ````css
 figure{
	margin: 1em 40px;
	text-align: center;
}
````

**Comment by bob-reus** [comment]
All fixed and committed, except this one, as I'm not sure how to go about it: 

>     * The blockquote CSS selectors for chapter 7-1 can be replaced with a class, because we have a class of elements to style.

I thought of this before, but I had, and have, a hard time thinking of a semantic class name. I'm still not 100% sure about the verse semantication either, as it's kind of ambiguous what these lines actually are.  I'd describe it as stylized, poetic prose, but nearly all class names I could think of would go against [SEMoS 1.1.7.4.2](https://standardebooks.org/manual/1.8.0/single-page#1.1.7.4.2). That's why I opted for the long list of selectors. Would something like `poetic-prose` work as a class name?

Here's a link to the scans for reference: [Jean Christophe 7-2 blockquote](https://archive.org/details/jeanchristophe02roll_0/page/326/mode/2up).

**Comment by bob-reus** [comment]
I reread the whole passage and something clicked, so I did a search for these lines from the French version of the book: these are fragments of French poems by Charles Guérin, Henri de Régnier, and others.

So technically, in accordance with SEMoS, I could remove the extra styling (italics). With so many blockquotes together, often with only a single line of prose in between, that does make the end result harder to read. 

Should I just take out the italics?

**Comment by acabal** [comment]
OK, yes, then they should be blockquotes without italics.

**Comment by bob-reus** [comment]
Done!
